#用户表
CREATE TABLE IF NOT EXISTS T_EXAMINEE (
    USER_PHONE VARCHAR(255) NOT NULL,
	ID_CARD VARCHAR(255),
    USER_NAME VARCHAR(255) NOT NULL,
    USER_SEX INT,
    USER_PROFESSION VARCHAR(255),
    LOGIN_PASSWORD VARCHAR(255) NOT NULL,
    PAY_PASSWORD VARCHAR(255),
    USER_PHOTO VARCHAR(255),
    RESIDENTIAL_ADDRESS VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    USER_BALANCE INT DEFAULT 0,
    LAST_LOGIN_TIME DATETIME,
    PRIMARY KEY (`USER_PHONE`)
);

drop table t_examinee;

select * from T_EXAMINEE;

insert into T_EXAMINEE 
(USER_PHONE,ID_CARD,USER_NAME,USER_SEX,USER_PROFESSION,LOGIN_PASSWORD,PAY_PASSWORD,USER_PHOTO,RESIDENTIAL_ADDRESS,EMAIL_ADDRESS,USER_BALANCE,LAST_LOGIN_TIME)
values
('18086709628','320582199602088511','徐至彦',1,'学生','111111','','','','664025900@qq.com',0,now());

insert into T_EXAMINEE 
(USER_PHONE,ID_CARD,USER_NAME,USER_SEX,USER_PROFESSION,LOGIN_PASSWORD,PAY_PASSWORD,USER_PHOTO,RESIDENTIAL_ADDRESS,EMAIL_ADDRESS,USER_BALANCE,LAST_LOGIN_TIME)
values
('15751861052','','徐至彦',1,'学生','111111','','','','664025900@qq.com',0,now());

SELECT COUNT(1) FROM T_EXAMINEE WHERE USER_PHONE = '18086709628' AND LOGIN_PASSWORD = '1111111'


#考试表
CREATE TABLE IF NOT EXISTS T_EXAM_MANAGEMENT (
	EXAM_ID VARCHAR(255) not null PRIMARY KEY,
	EXAM_NAME VARCHAR(255) NOT NULL,
	COST INT,
	MAX_NUM INT,
	EXAM_PLACE VARCHAR(255),
	EXAM_TIME_FROM DATETIME,
	EXAM_TIME_TO DATETIME,
	REG_TIME_FROM DATETIME,
	REG_TIME_TO DATETIME
);

select * from oerts.T_EXAM_MANAGEMENT;

drop table oerts.T_EXAM_MANAGEMENT;

insert into T_EXAM_MANAGEMENT
(EXAM_ID, EXAM_NAME, COST, MAX_NUM, EXAM_PLACE, EXAM_TIME_FROM, EXAM_TIME_TO, REG_TIME_FROM, REG_TIME_TO)
values
('1000001','2018年上半年CET-4', 30, 500, '', now(), now(), now(), now())

insert into T_EXAM_MANAGEMENT
(EXAM_ID, EXAM_NAME, COST, MAX_NUM, EXAM_PLACE, EXAM_TIME_FROM, EXAM_TIME_TO, REG_TIME_FROM, REG_TIME_TO)
values
('1000002','2018年上半年CET-6', 35, 400, '', now(), now(), now(), now())

insert into T_EXAM_MANAGEMENT
(EXAM_ID, EXAM_NAME, COST, MAX_NUM, EXAM_PLACE, EXAM_TIME_FROM, EXAM_TIME_TO, REG_TIME_FROM, REG_TIME_TO)
values
('1000003','2018年上半年软考-初级', 140, 100, '', now(), now(), now(), now())

insert into T_EXAM_MANAGEMENT
(EXAM_ID, EXAM_NAME, COST, MAX_NUM, EXAM_PLACE, EXAM_TIME_FROM, EXAM_TIME_TO, REG_TIME_FROM, REG_TIME_TO)
values
('1000004','2018年上半年软考-中级', 140, 50, '', now(), now(), now(), now())

insert into T_EXAM_MANAGEMENT
(EXAM_ID, EXAM_NAME, COST, MAX_NUM, EXAM_PLACE, EXAM_TIME_FROM, EXAM_TIME_TO, REG_TIME_FROM, REG_TIME_TO)
values
('1000005','2018年上半年软考-高级', 140, 10, '', now(), now(), now(), now())

#报名表
CREATE TABLE IF NOT EXISTS T_EXAM_REGISTRATION (
	ID_CARD VARCHAR(255) not null,
	EXAM_ID VARCHAR(255) not null,
	ADMISSION_TICKET VARCHAR(255),
	STATUS VARCHAR(2),
	SCORE int,
	PRIMARY KEY (`ID_CARD`, `EXAM_ID`)
);

INSERT INTO T_EXAM_REGISTRATION VALUES('111','111','111','11',0)

身份证
准考证
姓名
手机号
状态（是否付费）


































